### ISSUE TITLE
Exceptions not imported properly into HubInstance

### ISSUE THREAD

**Issue by skiyooka** [blackducksoftware/hub-rest-api-python#159]
Hey @AR-Calder I don't think Exceptions are being properly imported into HubInstance. For example the following fails if you try and run it twice.

```
from blackduck.HubRestApi import HubInstance

hub = HubInstance(
    "https://your.blackduck.url",
    api_token="token",
    insecure=True,
)

r = hub.create_user_group_by_name("test-group")
print(r)
print(r.text)
```

Exception:
```
Traceback (most recent call last):
  File "/Users/skiyooka/Library/Application Support/JetBrains/IdeaIC2021.1/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/skiyooka/Library/Application Support/JetBrains/IdeaIC2021.1/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/skiyooka/work_code/github/hub-rest-api-python/sumio_hub_instance.py", line 12, in <module>
    r = hub.create_user_group_by_name("test-group")
  File "/Users/skiyooka/work_code/github/hub-rest-api-python/blackduck/UserGroup.py", line 38, in create_user_group_by_name
    return self.create_user_group(user_group_info)
  File "/Users/skiyooka/work_code/github/hub-rest-api-python/blackduck/UserGroup.py", line 29, in create_user_group
    location = self._create(url, user_group_json)
  File "/Users/skiyooka/work_code/github/hub-rest-api-python/blackduck/Core.py", line 166, in _create
    raise CreateFailedAlreadyExists("Failed to create the object because it already exists - url {}, body {}, response {}".format(url, json_body, response))
NameError: name 'CreateFailedAlreadyExists' is not defined
```

I tried a quick fix to add the following to HubRestApi.py but I am not able to get it working. Do you have any cycles this weekend and/or do you see an obvious fix?

```
from .Exceptions import (
    CreateFailedAlreadyExists, CreateFailedUnknown, InvalidVersionPhase, UnknownVersion, UnsupportedBDVersion,
    EndpointNotFound, UnacceptableContentType
)
```

**Comment by AR-Calder** [comment]
I'll take a look into this tomorrow.

**Comment by AR-Calder** [comment]
As the exceptions are not members of the HubInstance class they will need to be imported whenever they are used. I'll push the fix after work tonight.
