### ISSUE TITLE
x-csrf-token does not exist

### ISSUE THREAD

**Issue by winmike** [blackducksoftware/hub-rest-api-python#216]
Calling the **scan_docker_image.py** to verify an image, following error appears (s. below).
**self.token, self.csrf_token, self.cookie = self.get_auth_token()** 
results in
**return self._store[key.lower()][1] 
KeyError: 'x-csrf-token'** 

Does it mean, the blackduck server response doesn't contain this header? What can be the reason - failed authentication?

_Traceback (most recent call last): 
File "/home/vsts/work/1/s/pipelines/blackduck/scan_docker_image_layers.py", line 538, in <module> 
sys.exit(main()) 
File "/home/vsts/work/1/s/pipelines/blackduck/scan_docker_image_layers.py", line 528, in main 
scan_container_image(args.imagespec) 
File "/home/vsts/work/1/s/pipelines/blackduck/scan_docker_image_layers.py", line 413, in scan_container_image 
hub = HubInstance() 
File "/home/vsts/.local/lib/python3.8/site-packages/blackduck/HubRestApi.py", line 157, in __init__ 
self.token, self.csrf_token, self.cookie = self.get_auth_token() 
File "/home/vsts/.local/lib/python3.8/site-packages/blackduck/Core.py", line 35, in get_auth_token 
csrf_token = response.headers['X-CSRF-TOKEN'] 
File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__ 
return self._store[key.lower()][1] 
KeyError: 'x-csrf-token'_

**Comment by shivabhatnutanix** [comment]
Seeing the same ussye 
>>> hub = HubInstance()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/blackduck/HubRestApi.py", line 155, in __init__
    self.token, self.csrf_token, self.cookie = self.get_auth_token()
  File "/usr/local/lib/python3.6/site-packages/blackduck/Core.py", line 35, in get_auth_token
    csrf_token = response.headers['X-CSRF-TOKEN']
  File "/usr/local/lib/python3.6/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-csrf-token'

**Comment by subhamsps** [comment]
i believe you might have added a '/' at the end of the url in .restconfig.json , please remove the '/' and try again

**Comment by winmike** [comment]
Indeed: the removal of the trailing slash did the trick Thank you!

**Comment by dineshr93** [comment]
In my case below steps worked
```
$ apt remove python3-pip
$ apt install python3-pip
$ pip3 install pyOpenSSL --upgrade
$ pip3 install blackduck
```
