### ISSUE TITLE
KeyError when run examples/client/get_project_vulnerabilites_as_csv.py

### ISSUE THREAD

**Issue by gtisan** [blackducksoftware/hub-rest-api-python#277]
I'm running this 
python examples/client/get_project_vulnerabilites_as_csv.py
and I get this error 
Traceback (most recent call last):
  File "hub-rest-api-python/examples/client/get_project_vulnerabilites_as_csv.py", line 92, in <module>
    main()
  File "hub-rest-api-python/examples/client/get_project_vulnerabilites_as_csv.py", line 79, in main
    remediation = vulnverable_component['vulnerabilityWithRemediation']
KeyError: 'vulnerabilityWithRemediation'

It seems that the key was renamed or removed. How is the name of the new key ?

**Comment by djeverett** [comment]
I've seen this too since we upgraded to Black Duck 2024.7.

**Comment by OffBy0x01** [comment]
If you drop a list resources in there you can see if there is an equivalent.

**Comment by djeverett** [comment]
Yes, the "href" resource does seem to have the equivalent info in it.
