### ISSUE TITLE
Error with JsonDecode modules.

### ISSUE THREAD

**Issue by ngboonhai** [blackducksoftware/hub-rest-api-python#44]
c:\Python37>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from blackduck.HubRestApi import HubInstance
>>> import json
>>> username = "xxxxx"
>>> password = "xxxxxx"
>>> urlbase = "https://xxxxxxx"
>>> hub = HubInstance(urlbase, username, password, insecure=True)
>>>
>>> projects = hub.get_projects()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python37\lib\site-packages\blackduck\HubRestApi.py", line 748, in get_projects
    jsondata = response.json()
  File "c:\Python37\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ngboonhai** [comment]
Found my current ProtexIP (Blackduck) server is not support API.
