### ISSUE TITLE
Latest code broken due to inconsistent indentation

### ISSUE THREAD

**Issue by ceejatec** [blackducksoftware/hub-rest-api-python#97]
`Traceback (most recent call last):
  File "./download-reports.py", line 11, in <module>
    from blackduck.HubRestApi import HubInstance
  File "/home/couchbase/jenkins/workspace/blackduck-reports/build-tools/blackduck/jenkins/generate-reports/.venv/lib/python3.6/site-packages/blackduck/HubRestApi.py", line 1685
    def get_matched_components(self, version_obj, limit=9999):
                                                             ^
TabError: inconsistent use of tabs and spaces in indentation
`

**Comment by gsnyder2007** [comment]
fixed, 0.0.48

**Comment by gsnyder2007** [comment]
as per @ceejatec this is resolved, closing
